Remove JndiLookup.class from log4j-core.jar classes
showheroes/incubator-druid pull request #9
Opened 2021-12-14 12:42 UTC by denever

2021-12-14 13:57 UTC, fxpz requested changes

2021-12-14 13:57 UTC, fxpz commented on distribution/docker/Dockerfile.viralize
> +COPY --from=zipper /zip /opt/zip
I think you could use directly `COPY --from=opsgang/zip`, better with a pinned tag

2021-12-14 14:07 UTC, denever commented on distribution/docker/Dockerfile.viralize
> +COPY --from=zipper /zip /opt/zip
Fixed

2021-12-16 09:07 UTC, fxpz approved these changes

2021-12-16 09:31 UTC, merged